# Azure DevOps pipeline template used to build bundle.

steps:
  - script: |
      yarn generate
    displayName: 'Generate definitions'
  - bash: |
      echo 'IO_PAY_PAYMENT_MANAGER_HOST: $IO_PAY_PAYMENT_MANAGER_HOST'
      echo 'IO_PAY_FUNCTIONS_HOST: $IO_PAY_FUNCTIONS_HOST'
      chmod +x env.sh && source env.sh
      yarn build
    env:
      IO_PAY_PAYMENT_MANAGER_HOST: $(IO_PAY_PAYMENT_MANAGER_HOST)
      IO_PAY_FUNCTIONS_HOST: $(IO_PAY_FUNCTIONS_HOST)
    displayName: 'Build files'
