# Azure DevOps pipeline template used to build bundle.
parameters:
  - name: 'api_host'
    type: string
    default: ''

  - name: 'env'
    type: string
    default: ''

steps:
  - script: |
      yarn generate
    displayName: 'Generate definitions'
  - bash: |
      echo 'IO_PAY_PAYMENT_MANAGER_HOST: $IO_PAY_PAYMENT_MANAGER_HOST'
      echo 'IO_PAY_FUNCTIONS_HOST: $IO_PAY_FUNCTIONS_HOST'
      echo 'IO_PAY_ENV: $IO_PAY_ENV'
      chmod +x env.sh && source env.sh
      yarn build
    env:
      IO_PAY_PAYMENT_MANAGER_HOST: ${{ parameters.api_host }}
      IO_PAY_FUNCTIONS_HOST: $(IO_PAY_FUNCTIONS_HOST)
      IO_PAY_ENV: ${{ parameters.env }}
    displayName: 'Build files'
