// import { debug } from 'console';
import { Server } from 'http';

import { Browser, launch } from 'puppeteer';
import { createHttpTerminator, HttpTerminator } from 'http-terminator';
import express from 'express';
import pmBad from './pmBad';

/**
 * This test suite tests the autogenerated client for PM in a browser
 * environment. The browser fetches index.html from the DevServer, which serves
 * from localhost:1235. When the DOM is loaded, a script inside index.html is
 * executed. The script creates a new instance of PM Client, configured with a
 * retryable fetch, to interact with the Bad PM on localhost:9666.
 * The Bad PM replies 429 to start-session POST, so the PM Client should retry
 * start-session many times. That way also the retryable fetch gets tested
 */
describe('PM Client', () => {
  const PORT = 1235;
  const HOST = 'localhost';

  // eslint-disable-next-line functional/no-let
  let myDevServer: Server;
  // eslint-disable-next-line functional/no-let
  let pmBadServer: Server;
  // eslint-disable-next-line functional/no-let
  let devServerTerminator: HttpTerminator;
  // eslint-disable-next-line functional/no-let
  let pmBadTerminator: HttpTerminator;

  // eslint-disable-next-line functional/no-let
  let myBrowser: Browser;

  beforeAll(() => {
    // Start server
    const myServer = express().use('/', express.static('testCases'));
    myDevServer = myServer.listen(PORT, HOST);
    devServerTerminator = createHttpTerminator({ server: myDevServer });

    pmBadServer = pmBad.listen(9666, 'localhost');
    pmBadTerminator = createHttpTerminator({ server: pmBadServer });
  });

  afterAll(async () => {
    await Promise.all([pmBadTerminator.terminate(), devServerTerminator.terminate()]);
  });

  beforeEach(async () => {
    myBrowser = await launch({ headless: true });
  });

  afterEach(async () => {
    await myBrowser.close();
  });

  it('should retry 3 times on start-session', async () => {
    const pmTab = await myBrowser.newPage();

    // eslint-disable-next-line functional/no-let
    let requestCounter = 0;

    // Intercept requests to count calls to start-session
    await pmTab.setRequestInterception(true);
    pmTab.on('request', async request => {
      if (request.method() === 'OPTIONS') {
        requestCounter++;
      }
      await request.continue();
    });

    const serverResponse = await pmTab.goto('http://localhost:1235/index.html');

    await new Promise(resolve => setTimeout(resolve, 4000));

    expect(serverResponse?.status()).toEqual(200);
    expect(requestCounter).toEqual(3);

    await pmTab.close();
  });
});
